---

- name: Compose the Minio client download base url
  set_fact:
    _minio_client_download_base_url: "https://dl.minio.io/client/mc/release/linux-{{ go_arch }}"
  tags:
    - download

- name: Compose the Minio client download url with lastest release
  set_fact:
    _minio_client_download_url: "{{ _minio_client_download_base_url }}/mc"
  when: minio_client_release | length == 0
  tags:
    - download

- name: "Compose the Minio client download url with release {{ minio_client_release }}"
  set_fact:
    _minio_client_download_url: "{{ _minio_client_download_base_url }}/archive/mc.{{ minio_client_release }}"
  when: minio_client_release | length > 0
  tags:
    - download

- name: "Get the Minio client checksum for {{ go_arch }} architecture"
  set_fact:
    _minio_client_checksum: "{{ lookup('url', _minio_client_download_url + '.sha256sum').split(' ')[0] }}"
  tags:
    - download

- name: "Download the Minio client checksum file for {{ go_arch }} architecture"
  get_url:
    url: "{{ _minio_client_download_url }}.sha256sum"
    dest: "{{ minio_client_bin }}.sha256sum"
  register: _download_client_checksum
  until: _download_client_checksum
  retries: 5
  delay: 2
  tags:
    - never
    - download

- name: Download the Minio client
  get_url:
    url: "{{ _minio_client_download_url }}"
    dest: "{{ minio_client_bin }}"
    checksum: "sha256:{{ _minio_client_checksum }}"
  register: _download_client
  until: _download_client is succeeded
  retries: 5
  delay: 2
  tags:
    - download

- name: Set attributes on Minio server binary
  file:
    path: "{{ minio_server_bin }}"
    owner: "root"
    group: "root"
    mode: 0755
  tags:
    - install
