---
- name: Compose the Minio server download base url
  set_fact:
    _minio_server_download_base_url: "https://dl.minio.io/server/minio/release/linux-{{ go_arch }}"
  tags:
    - download

- name: Compose the Minio server download url with lastest release
  set_fact:
    _minio_server_download_url: "{{ _minio_server_download_base_url }}/minio"
  when: minio_server_release | length == 0
  tags:
    - download

- name: "Compose the Minio server download url with release {{ minio_server_release }}"
  set_fact:
    _minio_server_download_url: "{{ _minio_server_download_base_url }}/archive/minio.{{ minio_server_release }}"
  when: minio_server_release | length > 0
  tags:
    - download

- name: "Get the Minio server checksum for {{ go_arch }} architecture"
  set_fact:
    _minio_server_checksum: "{{ lookup('url', _minio_server_download_url + '.sha256sum').split(' ')[0] }}"
  tags:
    - download

- name: "Download the Minio server checksum file for {{ go_arch }} architecture"
  get_url:
    url: "{{ _minio_server_download_url }}.sha256sum"
    dest: "{{ minio_server_bin }}.sha256sum"
  register: _download_server_checksum
  until: _download_server_checksum
  retries: 5
  delay: 2
  tags:
    - never
    - download

- name: Create Minio group
  group:
    name: "{{ minio_group }}"
    state: present
  tags:
    - install

- name: Create Minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: "yes"
    shell: "/usr/sbin/nologin"
  tags:
    - install

- name: layout dump
  debug:
    msg: "using layout {{ layout }}."
  tags:
    - install


- name: Create the Minio data storage directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0750
  when: minio_server_make_datadirs|bool
  with_items: "{{ layouts[layout]['minio_server_datadirs'] }}"
  tags:
    - install

- name: Download the Minio server
  get_url:
    url: "{{ _minio_server_download_url }}"
    dest: "{{ minio_server_bin }}"
    checksum: "sha256:{{ _minio_server_checksum }}"
  register: _download_server
  until: _download_server is succeeded
  retries: 5
  delay: 2
  tags:
    - download

- name: Set attributes on Minio server binary
  file:
    path: "{{ minio_server_bin }}"
    owner: "root"
    group: "root"
    mode: 0755
  notify: restart minio
  tags:
    - install

- name: Identify all of the cluster members
  set_fact:
    minio_cluster_nodes: >-
      {% for layout in layouts %}
        {% for host in groups["minio"] %}
          [
            'http://',
            hostvars[host]['ansible_' + minio_network_interface]['ipv4']['address'],
            layouts[layout]['minio_server_addr'],
            layouts[layout]['minio_server_datadirs'],
            ' '
          ] | join('')
        {% endfor %}
      {% endfor %}
  tags:
    - install

- name: cluster dump
  debug:
    msg: "using cluster map {{ minio_cluster_nodes }}."
  tags:
    - install


- name: Generate the Minio server envfile
  template:
    src: minio.env.j2
    dest: "{{ layouts[layout]['minio_server_envfile'] }}"
    owner: "root"
    group: "{{ minio_group }}"
    mode: 0640
  notify: restart minio
  tags:
    - install

- name: Create the Minio server systemd config
  template:
    src: minio.service.j2
    dest: "/etc/systemd/system/{{ layouts[layout]['servicename'] }}.service"
    owner: "root"
    group: "root"
  when: ansible_service_mgr == "systemd"
  notify:
    - reload minio systemd
    - restart minio
  tags:
    - install
    -
- name: Create the Minio server init.d config
  template:
    src: minio.init.j2
    dest: "/etc/init.d/{{ layouts[layout]['servicename'] }}"
    owner: "root"
    group: "root"
    mode: 0750
  when: ansible_service_mgr != "systemd"
  notify: restart minio
  tags:
    - install

- name: Enable and start the Minio service
  service:
    name: "{{ layouts[layout]['servicename'] }}"
    state: started
    enabled: true
  tags:
    - install
