---
- name: Add sni support to legacy python installations
  import_tasks: python_sni.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_python_version is version_compare('2.6.0', '>=')
    - ansible_python_version is version_compare('2.7.9', '<')

- import_tasks: setup.yml

- import_tasks: install-server.yml
  when: minio_install_server|bool

- import_tasks: install-client.yml
  when: minio_install_client|bool
